# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI for fullstack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./codebase/rdicidr-0.1.0
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 15
      uses: actions/setup-node@v4
      with:
        node-version: '15'
        cache: 'npm'
        cache-dependency-path: "./codebase/rdicidr-0.1.0/package-lock.json"
    - run: npm ci
    - run: npm run lint
    - run: npm run format
    - run: npm run prettier
    - run: CI=true npm run test
    - run: npm run build --if-present

  build-image:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./codebase/rdicidr-0.1.0
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.AWS_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG