# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI for fullstack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./codebase/rdicidr-0.1.0
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 15
      uses: actions/setup-node@v4
      with:
        node-version: '15'
        cache: 'npm'
        cache-dependency-path: "./codebase/rdicidr-0.1.0/package-lock.json"
    - run: npm ci
    - run: npm run lint
    - run: npm run format
    - run: npm run prettier
    - run: CI=true npm run test
    - run: npm run build --if-present
